# Generated by Django 2.2.11 on 2020-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_type_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('last_activity_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('owner_user_id', models.IntegerField()),
                ('owner_display_name', models.CharField(max_length=100, null=True)),
                ('accepted_answer_id', models.IntegerField(null=True)),
                ('tags', models.TextField(null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('last_edit_user_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('closed_date', models.DateTimeField(null=True)),
                ('view_count', models.IntegerField(null=True)),
                ('last_edit_date', models.DateTimeField(null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('favorite_count', models.IntegerField(null=True)),
            ],
        ),
    ]
